### PR TITLE
chore: use `alpine:3.21.0` as base image

### PR DESCRIPTION
**Pull request by biscout42**
Main goal of this commit is to remediate CVEs in the base image https://hub.docker.com/layers/library/alpine/3.20.1/images/sha256-dabf91b69c191a1a0a1628fd6bdd029c0c4018041c7f052870bb13c5a222ae76?context=explore

### CODE REVIEW

**Comment by biscout42** [comment]
@Abhinandan-Purkait , could you help with review?

**Review by Abhinandan-Purkait — APPROVED** [review]

**Comment by Abhinandan-Purkait** [comment]
Looks good to me. Looping in @tiagolobocastro @niladrih

**Review by niladrih — APPROVED** [review]

**Review by tiagolobocastro — APPROVED** [review]

**Comment by tiagolobocastro** [comment]
@niladrih also somewhat related to the security process we discussed today, would be nice to get GitHub or dependabot alerts for these Dockerfiles (if possible)

**Comment by niladrih** [comment]
> @niladrih also somewhat related to the security process we discussed today, would be nice to get GitHub or dependabot alerts for these Dockerfiles (if possible)

Sure, I'll create a GitHub issue for this. I'll investigate..

**Comment by niladrih** [comment]
https://github.com/openebs/openebs/issues/3815

**Pull request merged**
